---
title: "Air-Yards-Distributions"
author: "Stephen Pelkofer"
date: "1/22/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Setup

```{r message = FALSE, warning=FALSE}
library(tidyverse)
library(nflfastR)
library(lubridate)
library(ggridges)
library(showtext)
font_add_google(name = "Sora", family = "Sora")
showtext_auto()
source("../functions/theme_sp.R")
```


# Get Player Data

```{r message=FALSE}
nfl_pbp <- load_pbp(2021)
```


```{r}
qbs <- tibble(
  player_id = c(
    "00-0026498", # Stafford
    "00-0031345", # Garoppolo
    "00-0023459", # Rodgers
    "00-0019596" # Brady
    ),
  name = c(
    "Matt Stafford",
    "Jimmy Garappolo",
    "Aaron Rodgers",
    "Tom Brady"
    ),
  team_color = c(
    "#003594",
    "#AA0000",
    "#203731",
    "#D50A0A"
    )
)
```


# Loop through players

```{r}
for (row in 1:nrow(qbs)) {
  # Get player info
  player_id = qbs$player_id[row]
  player = qbs$name[row]
  team_color = qbs$team_color[row]
  
  
  # player air yards
  player_air_yards <- nfl_pbp %>% 
    # Filter to player and regular season
    filter(
      season_type == "REG", 
      passer_player_id == player_id,
      complete_pass == 1
    )  %>% 
    select(
      game_id, season_type, week,
      passer_player_id, passer_player_name, air_yards
    ) %>% 
    mutate(
      air_yards = case_when(
        air_yards < 0 ~ 0, # Change negative yards to 0
        air_yards > 30 ~ 30, # Group >= 30
        TRUE ~ air_yards
      )
    )
  
  # total completions
  n_completions <- nrow(player_air_yards)
  
  # Group by distance
  distance_summary <- player_air_yards %>% 
    group_by(air_yards) %>% 
    summarise(
      n = n(),
      .groups = "drop"
    ) %>%
    mutate(
      # For geom_point
      dummy_0 = 0,
      bin_size = factor(
          case_when(
          n <= 5 ~ "0-5",
          n <= 10 ~ "6-10",
          n <= 20 ~ "11-20",
          n >= 21 ~ "21+",
          TRUE ~ "None"
        ),
        levels = c("0-5", "6-10", "11-20", "21+")
      ),
      curve_size = case_when(
        n <= 5 ~ .25,
        n <= 10 ~ .5,
        n <= 20 ~ .8,
        n >= 21 ~ 1.3,
        TRUE ~ 0
      )
    )
  
  # Median Air Yards
  med_dist <- round(median(player_air_yards$air_yards))
  
  p <- ggplot() +
    #scale_y_continuous(limits = c(-.04,1), expand = c(0,0)) +
    scale_x_continuous(
      limits = c(0,32),
      breaks = c(0,5,10,15,20,25,30),
      labels = c("0 AIR YARDS", "5", "10", "15", "20", "25", "30+")
    ) +
    geom_segment(
      aes(x = med_dist, y = 0, xend = med_dist, yend = .25),
      color = "#252525",
      size = .3,
      linetype = "dashed"
    ) +
    geom_hline(
      aes(yintercept = 0),
      color = "#252525",
      size = .9
    ) +
    labs(
      title = glue::glue("{player} Air-Yards on Complete Passes"),
      subtitle = glue::glue("2021 NFL Season: {n_completions} completions"),
      x = "",
      y = "",
      size = "",
      caption = ""
    ) +
    theme_sp(
      title_family = "Sora",
      text_family = "Sora",
      plots_pane = FALSE,
      base_size = 13
    ) +
    theme(
      axis.line = element_blank(),
      axis.text.y = element_blank(),
      panel.grid = element_blank(),
      axis.ticks.x = element_line(color = "#bdbdbd"),
      axis.ticks.length = unit(.25, "cm")
    )
  
  # Draw curves
  for (row in 1:nrow(distance_summary)) {
    curve_data <- tibble(
      distance = distance_summary$air_yards[row],
      curve_size = distance_summary$curve_size[row]
    )
  
    if (curve_data$distance != 0) {
      p <- p +
      geom_curve(
        data = curve_data,
        aes(
          x = 0, 
          y = 0, 
          xend = distance, 
          yend = 0
        ), 
        colour = team_color, 
        size = distance_summary$curve_size[row],
        curvature = -1
      )
    }
  }
  
  p +
    geom_point(
      data = distance_summary,
      aes(x = air_yards, y = dummy_0, size = bin_size),
      shape = 21,
      color = "white",
      fill = team_color,
      alpha = 1
    ) +
    scale_size_manual(
      values = c(
        "0-5"= 2,
        "6-10"= 4,
        "11-20"= 6,
        "21+"= 10
      )
    ) +
    ggsave(glue::glue("{player}.png"),device = "png", width = 12, height = 8, dpi = 300)
}
```
